### ISSUE TITLE
error when launching pv

### ISSUE THREAD

**Issue by franshesco** [roccomuso/pv#2]
Hello, I have install pv through nodejs but I have the following error when I try to use it

`/usr/local/lib/node_modules/pv/bin/pv.js:28
  stderr(`${name} ${percentage} | ${eta} | ${transferred} | ${speed}`)
         ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
`
I don't really understand

thx

**Comment by roccomuso** [comment]
what version of node are you using?

`node -v`

**Comment by franshesco** [comment]
Hi @roccomuso ,

the version is below
`# node -v
v0.10.30
`
thx

**Comment by roccomuso** [comment]
That's why. You should upgrade and put node v6. :)

**Comment by franshesco** [comment]
okay thx you, I will try

**Comment by franshesco** [comment]
Hi @roccomuso ,

it works but when I try you command example, the result is surprising 
`# cat /dev/urandom | pv --size 100MB > /dev/null`
` 100% | 0 ETA | 969.13MB Transferred | 117.47MB/s`
The size in the progression is more than the one indicated. I thought that normally the operation would end when approaching the 100 MB.

thx

**Comment by roccomuso** [comment]
No. The Pipe viewer will not stop the pipe flow once reached 100MB. This is a tool to inspect the pipe flow, not to alter it :)
The size passed to the pv command is required just to estimate an ETA time and a % progress.

**Comment by franshesco** [comment]
okay thx
